"use client";

import Image from "next/image";
import FadeIn from "@/components/beyond/FadeIn";
import Parallax from "@/components/beyond/Parallax";
import SplitText from "@/components/beyond/SplitText";

export default function MissionPage() {
  return (
    <>
      {/* ── Section 1: Hero ── */}
      <section className="relative px-8 py-24 min-h-[819px] flex flex-col justify-end overflow-hidden">
        {/* Background motif */}
        <Parallax speed={0.3} className="absolute inset-0 pointer-events-none">
          <div className="absolute right-0 top-0 w-1/2 h-full">
            <Image
              src="/images/beyond/hero-engine-motif.jpg"
              alt=""
              fill
              unoptimized
              className="object-cover opacity-20 grayscale mix-blend-screen"
            />
          </div>
        </Parallax>

        {/* Content */}
        <div className="relative z-10 max-w-5xl">
          <FadeIn delay={0.1}>
            <p className="text-beyond-tertiary text-sm font-mono tracking-widest uppercase mb-6">
              Why Beyond Exists
            </p>
          </FadeIn>

          <SplitText
            as="h1"
            className="font-headline text-5xl md:text-7xl lg:text-8xl font-bold leading-[1.05] mb-8"
          >
            THE MARKET IS SHIFTING.
          </SplitText>

          <FadeIn delay={0.4}>
            <h2 className="font-headline text-3xl md:text-5xl lg:text-6xl font-bold text-beyond-tertiary mb-8">
              We&apos;re accelerating it.
            </h2>
          </FadeIn>

          <FadeIn delay={0.6} y={30}>
            <p className="text-beyond-on-surface-variant text-lg md:text-xl max-w-2xl leading-relaxed">
              AI acceleration has hit an inflection point. The clock speed of the
              world has increased and will keep getting faster. Clients need a new
              form of business that can help them transform to seize and sustain
              this advantage.
            </p>
          </FadeIn>
        </div>
      </section>

      {/* ── Section 2: Consultancies Can't Adapt ── */}
      <section className="bg-beyond-surface-low py-32 px-8">
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
          {/* Left column */}
          <FadeIn>
            <div>
              <p className="text-beyond-tertiary text-sm font-mono tracking-widest uppercase mb-4">
                The Problem
              </p>
              <h2 className="font-headline text-4xl md:text-5xl font-bold mb-6">
                Consultancies Can&apos;t Adapt.
              </h2>
              <p className="text-beyond-on-surface-variant text-lg leading-relaxed mb-10">
                Hundreds of thousands of employees, built for a world that
                changes over years, not weeks. Hard to adapt. Hard to scale.
                Share prices already tell the story. Clients need more agility,
                more speed, and lower costs.
              </p>

              {/* Info cards */}
              <div className="space-y-4">
                <div className="monolith-border rounded-xl p-6 flex items-start gap-4">
                  <span className="material-symbols-outlined text-beyond-tertiary text-3xl mt-0.5">
                    groups
                  </span>
                  <div>
                    <h3 className="font-headline text-lg font-semibold mb-1">
                      Headcount as a Metric
                    </h3>
                    <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                      Legacy firms measure success by team size, not impact.
                      More people, more billing &mdash; regardless of whether the
                      client&apos;s problem gets solved.
                    </p>
                  </div>
                </div>

                <div className="monolith-border rounded-xl p-6 flex items-start gap-4">
                  <span className="material-symbols-outlined text-beyond-tertiary text-3xl mt-0.5">
                    update_disabled
                  </span>
                  <div>
                    <h3 className="font-headline text-lg font-semibold mb-1">
                      Blind to Disruption
                    </h3>
                    <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                      Clients are not blind to AI&apos;s disruptive potential
                      &mdash; but their consultancies are. 30% of GitHub commits
                      will be AI-generated by end of 2026. The incumbents
                      aren&apos;t ready.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </FadeIn>

          {/* Right column */}
          <FadeIn delay={0.2}>
            <div className="relative">
              <div className="bg-beyond-surface-highest rounded-2xl overflow-hidden">
                <Image
                  src="/images/beyond/newspaper.jpg"
                  alt="Industry headlines"
                  width={640}
                  height={420}
                  unoptimized
                  className="w-full h-auto object-cover"
                />
              </div>

              {/* Stat badge */}
              <div className="absolute top-4 right-4 bg-beyond-tertiary text-black text-xs font-mono font-bold tracking-wider px-3 py-1.5 rounded-full uppercase">
                4% &rarr; 30% AI-Generated Code by 2026
              </div>

              {/* Blockquote */}
              <blockquote className="mt-8 border-l-2 border-beyond-tertiary pl-6">
                <p className="text-beyond-on-surface-variant text-lg italic leading-relaxed">
                  &ldquo;Agencies of the future will look more like software
                  companies, with software margins.&rdquo;
                </p>
              </blockquote>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* ── Section 3: SaaS is Dead ── */}
      <section className="py-32 px-8 bg-beyond-surface">
        <div className="max-w-5xl mx-auto text-center mb-16">
          <FadeIn>
            <SplitText
              as="h2"
              className="font-headline text-4xl md:text-6xl font-bold mb-6"
            >
              SaaS is Dead.
            </SplitText>
          </FadeIn>
          <FadeIn delay={0.2}>
            <p className="text-beyond-on-surface-variant text-lg md:text-xl max-w-2xl mx-auto leading-relaxed">
              Customers want outcomes, not more tools and licenses. They are
              frustrated by the slow pace of new features, the high cost of
              seats, and the disruption of changing their business to fit the
              software. The value in SaaS platforms is fast eroding.
            </p>
          </FadeIn>
        </div>

        <FadeIn stagger={0.15} className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Card 1 */}
            <div className="bg-beyond-surface-low rounded-2xl p-8 flex flex-col items-start">
              <span className="material-symbols-outlined text-beyond-tertiary text-4xl mb-6">
                license
              </span>
              <h3 className="font-headline text-xl font-semibold mb-3">
                Outcomes Over Licenses
              </h3>
              <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                Stop paying for tools your team barely uses. We deliver
                measurable results &mdash; not seats, not shelfware. You pay
                for what gets done.
              </p>
            </div>

            {/* Card 2 — elevated */}
            <div className="bg-beyond-surface-container rounded-2xl p-8 flex flex-col items-start scale-105 z-10 shadow-2xl shadow-black">
              <span className="material-symbols-outlined text-beyond-tertiary text-4xl mb-6">
                auto_awesome
              </span>
              <h3 className="font-headline text-xl font-semibold mb-3">
                Software That Fits You
              </h3>
              <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                Instead of changing your business to fit the software, we build
                AI products shaped around your frontline reality &mdash; your
                brand, your workflows, your customers.
              </p>
            </div>

            {/* Card 3 */}
            <div className="bg-beyond-surface-low rounded-2xl p-8 flex flex-col items-start">
              <span className="material-symbols-outlined text-beyond-tertiary text-4xl mb-6">
                trending_up
              </span>
              <h3 className="font-headline text-xl font-semibold mb-3">
                Agency Insight, Software Margins
              </h3>
              <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                When AI agents replace headcount, you get elite consulting
                insight with software economics. We operate with agility but
                scale with the unit economics of a platform.
              </p>
            </div>
          </div>
        </FadeIn>
      </section>

      {/* ── Section 4: The Beyond Difference ── */}
      <section className="py-32 px-8 bg-beyond-surface-low">
        <div className="max-w-5xl mx-auto">
          <FadeIn>
            <div className="text-center mb-16">
              <p className="text-beyond-tertiary text-sm font-mono tracking-widest uppercase mb-4">
                The Solution
              </p>
              <h2 className="font-headline text-4xl md:text-5xl font-bold mb-6">
                A New Breed of Partner
              </h2>
              <p className="text-beyond-on-surface-variant text-lg max-w-2xl mx-auto leading-relaxed">
                Beyond is an AI-native agency and technology partner designed to
                disrupt legacy consultancies and traditional SaaS models by
                delivering frontline AI products at accelerated speeds.
              </p>
            </div>
          </FadeIn>

          <FadeIn stagger={0.1}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="monolith-border rounded-xl p-8">
                <span className="material-symbols-outlined text-beyond-tertiary text-3xl mb-4 block">
                  speed
                </span>
                <h3 className="font-headline text-xl font-semibold mb-3">
                  Weeks, Not Quarters
                </h3>
                <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                  Our proprietary AI-agent architecture means we ship production
                  AI products in weeks. No 6-month discovery phases. No
                  99-slide decks before a line of code is written.
                </p>
              </div>

              <div className="monolith-border rounded-xl p-8">
                <span className="material-symbols-outlined text-beyond-tertiary text-3xl mb-4 block">
                  storefront
                </span>
                <h3 className="font-headline text-xl font-semibold mb-3">
                  Built for the Frontline
                </h3>
                <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                  We&apos;ve spent decades building AI experiences for store
                  managers, field engineers, and customer-facing teams across
                  30+ global brands in retail, FMCG, defence, and luxury.
                </p>
              </div>

              <div className="monolith-border rounded-xl p-8">
                <span className="material-symbols-outlined text-beyond-tertiary text-3xl mb-4 block">
                  smart_toy
                </span>
                <h3 className="font-headline text-xl font-semibold mb-3">
                  Proprietary AI Engine
                </h3>
                <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                  The Infinity Engine is our agentic operating system &mdash;
                  six specialised AI agents that handle everything from research
                  to UX design to deployment and monitoring.
                </p>
              </div>

              <div className="monolith-border rounded-xl p-8">
                <span className="material-symbols-outlined text-beyond-tertiary text-3xl mb-4 block">
                  monitoring
                </span>
                <h3 className="font-headline text-xl font-semibold mb-3">
                  Outcome-Linked Value
                </h3>
                <p className="text-beyond-on-surface-variant text-sm leading-relaxed">
                  We don&apos;t bill hours. Our delivery model links commercial
                  success to the outcomes we generate &mdash; reduced costs,
                  increased efficiency, top-line growth.
                </p>
              </div>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* ── Section 5: CTA ── */}
      <section className="relative py-40 px-8 bg-beyond-surface-lowest overflow-hidden">
        {/* Dot-grid background */}
        <div
          className="absolute inset-0 opacity-10 pointer-events-none"
          style={{
            backgroundImage:
              "radial-gradient(circle at 2px 2px, #ffffff 1px, transparent 0)",
            backgroundSize: "40px 40px",
          }}
        />

        <div className="relative z-10 max-w-3xl mx-auto text-center">
          <FadeIn>
            <SplitText
              as="h2"
              className="font-headline text-4xl md:text-6xl font-bold mb-10"
            >
              Ready to go beyond?
            </SplitText>
          </FadeIn>

          <FadeIn delay={0.3} y={20}>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <a
                href="/contact"
                className="kinetic-gradient px-8 py-4 rounded-full text-white font-semibold text-lg transition-transform hover:scale-105"
              >
                Partner with Beyond
              </a>
              <a
                href="/solutions"
                className="bg-beyond-surface-high px-8 py-4 rounded-full text-beyond-on-surface font-semibold text-lg transition-transform hover:scale-105"
              >
                See Our Solutions
              </a>
            </div>
          </FadeIn>
        </div>
      </section>
    </>
  );
}
